# Generated by Django 4.2.26 on 2025-11-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnertype',
            options={'verbose_name': 'Тип партнера', 'verbose_name_plural': 'Типы партнеров'},
        ),
        migrations.AlterField(
            model_name='partnertype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название типа'),
        ),
    ]
