# Generated by Django 4.2.26 on 2025-11-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_partnertype_options_alter_partnertype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercontact',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
